[versions]
accompanistSystemuicontroller = "0.34.0-alpha"
agp = "8.8.2"
billingKtx = "8.0.0"
cameraCamera2 = "1.4.2"
cameraLifecycleVersion = "1.4.2"
cameraViewVersion = "1.4.2"
coilCompose = "2.4.0"
coreVersion = "1.50.0"
datastorePreferences = "1.1.7"
googleCore = "1.50.0"
kotlin = "2.0.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxCoroutinesPlayServices = "1.8.1"
languageId = "17.0.6"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.10.1"
composeBom = "2025.08.01"
materialIconsExtended = "1.7.8"
materialVersion = "1.9.0"
okhttp = "4.12.0"
opencvAndroid = "4.5.1"
playServicesAds = "24.5.0"
room = "2.7.2"
hilt = "2.51"
hilt-navigation-compose = "1.2.0"
material = "1.13.0"
cameraView = "1.4.2"
playServicesMlkitTextRecognitionCommon = "19.1.0"
roomCompiler = "2.7.2"
tesseract4android = "5.3.2"
tessTwo = "9.1.0"
textRecognition = "16.0.1"
textRecognitionChinese = "16.0.1"
textRecognitionDevanagari = "16.0.1"
textRecognitionJapanese = "16.0.1"
textRecognitionKorean = "16.0.1"
ui = "1.9.0"
visionCommon = "17.3.0"
cameraLifecycle = "1.4.2"
playServicesMlkitTextRecognition = "19.0.1"
lifecycleProcess = "2.9.3"
toolsCore = "1.0.0-alpha13"
core = "1.50.0"
storage = "1.6.0"
roomCommonJvm = "2.7.2"
reviewKtx = "2.0.2"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCamera2" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCamera2" }
androidx-camera-lifecycle-v142 = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraLifecycleVersion" }
androidx-camera-view-v142 = { module = "androidx.camera:camera-view", version.ref = "cameraViewVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-room-compiler-v271 = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
core-v1480 = { module = "com.google.ar:core", version.ref = "googleCore" }
core-v1500 = { module = "com.google.ar:core", version.ref = "coreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
language-id = { module = "com.google.mlkit:language-id", version.ref = "languageId" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
opencv-android = { module = "org.opencv:opencv-android", version.ref = "opencvAndroid" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-mlkit-text-recognition-common = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition-common", version.ref = "playServicesMlkitTextRecognitionCommon" }
tess-two = { module = "com.rmtheis:tess-two", version.ref = "tessTwo" }
tesseract4android = { module = "cz.adaptech.tesseract4android:tesseract4android", version.ref = "tesseract4android" }
text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "textRecognition" }
text-recognition-chinese = { module = "com.google.mlkit:text-recognition-chinese", version.ref = "textRecognitionChinese" }
text-recognition-devanagari = { module = "com.google.mlkit:text-recognition-devanagari", version.ref = "textRecognitionDevanagari" }
text-recognition-japanese = { module = "com.google.mlkit:text-recognition-japanese", version.ref = "textRecognitionJapanese" }
text-recognition-korean = { module = "com.google.mlkit:text-recognition-korean", version.ref = "textRecognitionKorean" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
vision-common = { group = "com.google.mlkit", name = "vision-common", version.ref = "visionCommon" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
play-services-mlkit-text-recognition = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition", version.ref = "playServicesMlkitTextRecognition" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
androidx-tools-core = { group = "androidx.privacysandbox.tools", name = "tools-core", version.ref = "toolsCore" }
core = { group = "com.google.ar", name = "core", version.ref = "core" }
androidx-storage = { group = "androidx.test.services", name = "storage", version.ref = "storage" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "reviewKtx" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.0-1.0.21" }
